//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int administratorId { get; set; }
        public string administratorName { get; set; }
        public string administratorSurname { get; set; }
        public string administratorUsername { get; set; }
        public string administratorPassword { get; set; }
    }
}
