//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibrayDatabaseEntities : DbContext
    {
        public LibrayDatabaseEntities()
            : base("name=LibrayDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Lend> Lends { get; set; }
        public virtual DbSet<logAdmin> logAdmins { get; set; }
        public virtual DbSet<logAuthor> logAuthors { get; set; }
        public virtual DbSet<logBook> logBooks { get; set; }
        public virtual DbSet<logCategory> logCategories { get; set; }
        public virtual DbSet<logLend> logLends { get; set; }
        public virtual DbSet<logMember> logMembers { get; set; }
        public virtual DbSet<logPublication> logPublications { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<Member> Members { get; set; }
        public virtual DbSet<Publication> Publications { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    
        [DbFunction("LibrayDatabaseEntities", "usp_AdministratorId")]
        public virtual IQueryable<usp_AdministratorId_Result> usp_AdministratorId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_AdministratorId_Result>("[LibrayDatabaseEntities].[usp_AdministratorId](@id)", idParameter);
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_AdministratorList")]
        public virtual IQueryable<usp_AdministratorList_Result> usp_AdministratorList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_AdministratorList_Result>("[LibrayDatabaseEntities].[usp_AdministratorList]()");
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_AuthorId")]
        public virtual IQueryable<usp_AuthorId_Result> usp_AuthorId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_AuthorId_Result>("[LibrayDatabaseEntities].[usp_AuthorId](@id)", idParameter);
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_AuthorList")]
        public virtual IQueryable<usp_AuthorList_Result> usp_AuthorList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_AuthorList_Result>("[LibrayDatabaseEntities].[usp_AuthorList]()");
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_Book")]
        public virtual IQueryable<usp_Book_Result> usp_Book()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_Book_Result>("[LibrayDatabaseEntities].[usp_Book]()");
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_BookId")]
        public virtual IQueryable<usp_BookId_Result> usp_BookId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_BookId_Result>("[LibrayDatabaseEntities].[usp_BookId](@id)", idParameter);
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_BookList")]
        public virtual IQueryable<usp_BookList_Result> usp_BookList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_BookList_Result>("[LibrayDatabaseEntities].[usp_BookList]()");
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_BookListId")]
        public virtual IQueryable<usp_BookListId_Result> usp_BookListId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_BookListId_Result>("[LibrayDatabaseEntities].[usp_BookListId](@id)", idParameter);
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_CategoryId")]
        public virtual IQueryable<usp_CategoryId_Result> usp_CategoryId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_CategoryId_Result>("[LibrayDatabaseEntities].[usp_CategoryId](@id)", idParameter);
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_CategoryList")]
        public virtual IQueryable<usp_CategoryList_Result> usp_CategoryList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_CategoryList_Result>("[LibrayDatabaseEntities].[usp_CategoryList]()");
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_Lend")]
        public virtual IQueryable<usp_Lend_Result> usp_Lend()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_Lend_Result>("[LibrayDatabaseEntities].[usp_Lend]()");
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_LendId")]
        public virtual IQueryable<usp_LendId_Result> usp_LendId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_LendId_Result>("[LibrayDatabaseEntities].[usp_LendId](@id)", idParameter);
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_LendList")]
        public virtual IQueryable<usp_LendList_Result> usp_LendList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_LendList_Result>("[LibrayDatabaseEntities].[usp_LendList]()");
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_MemberId")]
        public virtual IQueryable<usp_MemberId_Result> usp_MemberId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_MemberId_Result>("[LibrayDatabaseEntities].[usp_MemberId](@id)", idParameter);
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_MemberList")]
        public virtual IQueryable<usp_MemberList_Result> usp_MemberList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_MemberList_Result>("[LibrayDatabaseEntities].[usp_MemberList]()");
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_PublicationId")]
        public virtual IQueryable<usp_PublicationId_Result> usp_PublicationId(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_PublicationId_Result>("[LibrayDatabaseEntities].[usp_PublicationId](@id)", idParameter);
        }
    
        [DbFunction("LibrayDatabaseEntities", "usp_PublicationList")]
        public virtual IQueryable<usp_PublicationList_Result> usp_PublicationList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<usp_PublicationList_Result>("[LibrayDatabaseEntities].[usp_PublicationList]()");
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual int usp_DeleteAdministrator(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteAdministrator", idParameter);
        }
    
        public virtual int usp_DeleteAuthor(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteAuthor", idParameter);
        }
    
        public virtual int usp_DeleteBook(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteBook", idParameter);
        }
    
        public virtual int usp_DeleteCategory(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteCategory", idParameter);
        }
    
        public virtual int usp_DeleteLend(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteLend", idParameter);
        }
    
        public virtual int usp_DeleteMember(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeleteMember", idParameter);
        }
    
        public virtual int usp_DeletePublication(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_DeletePublication", idParameter);
        }
    
        public virtual int usp_ImportAdministrator(string administratorName, string administratorSurname, string administratorUsername, string administratorPassword)
        {
            var administratorNameParameter = administratorName != null ?
                new ObjectParameter("administratorName", administratorName) :
                new ObjectParameter("administratorName", typeof(string));
    
            var administratorSurnameParameter = administratorSurname != null ?
                new ObjectParameter("administratorSurname", administratorSurname) :
                new ObjectParameter("administratorSurname", typeof(string));
    
            var administratorUsernameParameter = administratorUsername != null ?
                new ObjectParameter("administratorUsername", administratorUsername) :
                new ObjectParameter("administratorUsername", typeof(string));
    
            var administratorPasswordParameter = administratorPassword != null ?
                new ObjectParameter("administratorPassword", administratorPassword) :
                new ObjectParameter("administratorPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportAdministrator", administratorNameParameter, administratorSurnameParameter, administratorUsernameParameter, administratorPasswordParameter);
        }
    
        public virtual int usp_ImportAuthor(string authorName, string authorSurname)
        {
            var authorNameParameter = authorName != null ?
                new ObjectParameter("authorName", authorName) :
                new ObjectParameter("authorName", typeof(string));
    
            var authorSurnameParameter = authorSurname != null ?
                new ObjectParameter("authorSurname", authorSurname) :
                new ObjectParameter("authorSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportAuthor", authorNameParameter, authorSurnameParameter);
        }
    
        public virtual int usp_ImportBook(string bookName, string categoryId, string publicationId, string auhorId)
        {
            var bookNameParameter = bookName != null ?
                new ObjectParameter("bookName", bookName) :
                new ObjectParameter("bookName", typeof(string));
    
            var categoryIdParameter = categoryId != null ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(string));
    
            var publicationIdParameter = publicationId != null ?
                new ObjectParameter("publicationId", publicationId) :
                new ObjectParameter("publicationId", typeof(string));
    
            var auhorIdParameter = auhorId != null ?
                new ObjectParameter("auhorId", auhorId) :
                new ObjectParameter("auhorId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportBook", bookNameParameter, categoryIdParameter, publicationIdParameter, auhorIdParameter);
        }
    
        public virtual int usp_ImportCategory(string categoryName)
        {
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportCategory", categoryNameParameter);
        }
    
        public virtual int usp_ImportLend(string lendTime, string lendLength, string memberId, string bookId)
        {
            var lendTimeParameter = lendTime != null ?
                new ObjectParameter("lendTime", lendTime) :
                new ObjectParameter("lendTime", typeof(string));
    
            var lendLengthParameter = lendLength != null ?
                new ObjectParameter("lendLength", lendLength) :
                new ObjectParameter("lendLength", typeof(string));
    
            var memberIdParameter = memberId != null ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(string));
    
            var bookIdParameter = bookId != null ?
                new ObjectParameter("bookId", bookId) :
                new ObjectParameter("bookId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportLend", lendTimeParameter, lendLengthParameter, memberIdParameter, bookIdParameter);
        }
    
        public virtual int usp_ImportMember(string memberName, string memberSurname)
        {
            var memberNameParameter = memberName != null ?
                new ObjectParameter("memberName", memberName) :
                new ObjectParameter("memberName", typeof(string));
    
            var memberSurnameParameter = memberSurname != null ?
                new ObjectParameter("memberSurname", memberSurname) :
                new ObjectParameter("memberSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportMember", memberNameParameter, memberSurnameParameter);
        }
    
        public virtual int usp_ImportPublication(string publicationName)
        {
            var publicationNameParameter = publicationName != null ?
                new ObjectParameter("publicationName", publicationName) :
                new ObjectParameter("publicationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ImportPublication", publicationNameParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_Login(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_Login", usernameParameter, passwordParameter);
        }
    
        public virtual int usp_UpdateAdministrator(string id, string administratorName, string administratorSurname, string administratorUsername, string administratorPassword)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var administratorNameParameter = administratorName != null ?
                new ObjectParameter("administratorName", administratorName) :
                new ObjectParameter("administratorName", typeof(string));
    
            var administratorSurnameParameter = administratorSurname != null ?
                new ObjectParameter("administratorSurname", administratorSurname) :
                new ObjectParameter("administratorSurname", typeof(string));
    
            var administratorUsernameParameter = administratorUsername != null ?
                new ObjectParameter("administratorUsername", administratorUsername) :
                new ObjectParameter("administratorUsername", typeof(string));
    
            var administratorPasswordParameter = administratorPassword != null ?
                new ObjectParameter("administratorPassword", administratorPassword) :
                new ObjectParameter("administratorPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateAdministrator", idParameter, administratorNameParameter, administratorSurnameParameter, administratorUsernameParameter, administratorPasswordParameter);
        }
    
        public virtual int usp_UpdateAuthor(string id, string authorName, string authorSurname)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var authorNameParameter = authorName != null ?
                new ObjectParameter("authorName", authorName) :
                new ObjectParameter("authorName", typeof(string));
    
            var authorSurnameParameter = authorSurname != null ?
                new ObjectParameter("authorSurname", authorSurname) :
                new ObjectParameter("authorSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateAuthor", idParameter, authorNameParameter, authorSurnameParameter);
        }
    
        public virtual int usp_UpdateBook(string id, string bookName, string categoryId, string publicationId, string authorId)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var bookNameParameter = bookName != null ?
                new ObjectParameter("bookName", bookName) :
                new ObjectParameter("bookName", typeof(string));
    
            var categoryIdParameter = categoryId != null ?
                new ObjectParameter("categoryId", categoryId) :
                new ObjectParameter("categoryId", typeof(string));
    
            var publicationIdParameter = publicationId != null ?
                new ObjectParameter("publicationId", publicationId) :
                new ObjectParameter("publicationId", typeof(string));
    
            var authorIdParameter = authorId != null ?
                new ObjectParameter("authorId", authorId) :
                new ObjectParameter("authorId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateBook", idParameter, bookNameParameter, categoryIdParameter, publicationIdParameter, authorIdParameter);
        }
    
        public virtual int usp_UpdateCategory(string id, string categoryName)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var categoryNameParameter = categoryName != null ?
                new ObjectParameter("categoryName", categoryName) :
                new ObjectParameter("categoryName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateCategory", idParameter, categoryNameParameter);
        }
    
        public virtual int usp_UpdateLend(string id, string lendTime, string lendLength, string memberId, string bookId)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var lendTimeParameter = lendTime != null ?
                new ObjectParameter("lendTime", lendTime) :
                new ObjectParameter("lendTime", typeof(string));
    
            var lendLengthParameter = lendLength != null ?
                new ObjectParameter("lendLength", lendLength) :
                new ObjectParameter("lendLength", typeof(string));
    
            var memberIdParameter = memberId != null ?
                new ObjectParameter("memberId", memberId) :
                new ObjectParameter("memberId", typeof(string));
    
            var bookIdParameter = bookId != null ?
                new ObjectParameter("bookId", bookId) :
                new ObjectParameter("bookId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateLend", idParameter, lendTimeParameter, lendLengthParameter, memberIdParameter, bookIdParameter);
        }
    
        public virtual int usp_UpdateMember(string id, string memberName, string memberSurname)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var memberNameParameter = memberName != null ?
                new ObjectParameter("memberName", memberName) :
                new ObjectParameter("memberName", typeof(string));
    
            var memberSurnameParameter = memberSurname != null ?
                new ObjectParameter("memberSurname", memberSurname) :
                new ObjectParameter("memberSurname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdateMember", idParameter, memberNameParameter, memberSurnameParameter);
        }
    
        public virtual int usp_UpdatePublication(string id, string publicationName)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var publicationNameParameter = publicationName != null ?
                new ObjectParameter("publicationName", publicationName) :
                new ObjectParameter("publicationName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_UpdatePublication", idParameter, publicationNameParameter);
        }
    
        public virtual ObjectResult<usp_ViewTable_Result> usp_ViewTable(string tableName)
        {
            var tableNameParameter = tableName != null ?
                new ObjectParameter("tableName", tableName) :
                new ObjectParameter("tableName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ViewTable_Result>("usp_ViewTable", tableNameParameter);
        }
    }
}
